/** A token as the theme switch needs it: its id and both values. */
export interface ThemeToken {
  readonly id: string;
  readonly path: string;
  readonly light: string;
  readonly dark: string;
}

/** The override's export name, as design_apply's codeOverride names it. */
export const THEME_TOGGLE_EXPORT = "withThemeToggle";

/**
 * A code override that switches the site between its tokens' light and dark values on click, starts from the visitor's
 * last choice or system theme, and remembers the choice. Browser APIs run only in effects and handlers, so the
 * statically rendered page stays valid.
 */
export function themeToggleCode(tokens: readonly ThemeToken[]): string {
  const values = tokens.map(
    ({ id, path, light, dark }) => `    // ${path}\n    "${id}": [${JSON.stringify(light)}, ${JSON.stringify(dark)}],`,
  );

  return [
    'import type { ComponentType } from "react"',
    'import { useEffect } from "react"',
    "",
    "// Generated by Sitewright from the project's color tokens: run theme_toggle_add again after adding tokens.",
    "const TOKENS: Record<string, [string, string]> = {",
    ...values,
    "}",
    "",
    'const KEY = "sitewright-theme"',
    "",
    'type Theme = "light" | "dark"',
    "",
    "function apply(theme: Theme) {",
    "    for (const [id, [light, dark]] of Object.entries(TOKENS)) {",
    '        document.body.style.setProperty(`--token-${id}`, theme === "dark" ? dark : light)',
    "    }",
    "    document.documentElement.dataset.theme = theme",
    "}",
    "",
    "function saved(): Theme {",
    "    const choice = localStorage.getItem(KEY)",
    "",
    '    if (choice === "light" || choice === "dark") {',
    "        return choice",
    "    }",
    "",
    '    return matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"',
    "}",
    "",
    `export function ${THEME_TOGGLE_EXPORT}(Component): ComponentType {`,
    "    return (props) => {",
    "        useEffect(() => apply(saved()), [])",
    "",
    "        return (",
    "            <Component",
    "                {...props}",
    "                onClick={() => {",
    '                    const next: Theme = document.documentElement.dataset.theme === "dark" ? "light" : "dark"',
    "",
    "                    localStorage.setItem(KEY, next)",
    "                    apply(next)",
    "                }}",
    "            />",
    "        )",
    "    }",
    "}",
    "",
  ].join("\n");
}
