import type { BriefQuestionInfo } from "../types/brief.ts";

/** How urgent a question is: essentials come first and block the start; the rest have fallbacks. */
export const BRIEF_PRIORITIES = ["essential", "recommended", "optional"] as const;

/**
 * What to ask before building or redesigning a site, in asking order within each priority. `propose` turns an open
 * question into concrete proposals made for this project; `fallback` is what to take when the user skips it (null:
 * it must be answered).
 */
export const BRIEF_QUESTIONS = {
  purpose: {
    group: "project",
    priority: "essential",
    ask: "What is the site for, and what one action should a visitor take?",
    why: "The page structure, the main call to action and which sections exist.",
    options: [
      "Get leads: book a call or send a request",
      "Sell a product or an app: sign up or buy",
      "Show work: a portfolio",
      "A launch or an event: join a waitlist or register",
      "Publish content: a blog or a magazine",
    ],
    propose: null,
    fallback: null,
  },
  deliverable: {
    group: "project",
    priority: "essential",
    ask: "Whose site is it: a client's, the user's own, or a template to sell on the Framer Marketplace?",
    why: "A template follows Framer's checklist (design_guide template): realistic placeholder content buyers replace, CMS for repeated items, a custom 404 and every page on a layout template.",
    options: ["A client's site", "My own site or product", "A Framer Marketplace template"],
    propose: null,
    fallback: "The user's own site.",
  },
  name: {
    group: "project",
    priority: "essential",
    ask: "What is the site or the brand called, and is there a tagline?",
    why: "The logo, page titles, metadata and the copy.",
    options: [],
    propose: null,
    fallback: "A working name you suggest, marked as a placeholder to replace.",
  },
  pages: {
    group: "project",
    priority: "essential",
    ask: "One long page, or a site map? Which pages?",
    why: "The work plan, the navigation and the layout template every page sits on.",
    options: [
      "One page and a 404",
      "Home, about, services or product, contact and a 404",
      "Plus a blog or case studies from the CMS",
      "Plus pricing and legal pages",
    ],
    propose: null,
    fallback: "A home page and a 404, plus legal pages when there is a form.",
  },
  references: {
    group: "look",
    priority: "essential",
    ask: "Which sites do they like, and what exactly in each? Which do they dislike? Is there a brand book or a Figma file?",
    why: "The direction. A Figma file turns the work into a move from Figma.",
    options: [],
    propose:
      "When there are no references, call marketplace_browse for the site's category and offer two or three directions with their live previews.",
    fallback: "The direction you propose from the marketplace and the design guide.",
  },
  mood: {
    group: "look",
    priority: "essential",
    ask: "How should the site feel, in three words?",
    why: "Type, color, spacing and motion; it goes into the written direction.",
    options: [
      "Calm and editorial",
      "Bold and loud",
      "Precise and technical",
      "Warm and human",
      "Quiet luxury",
      "Playful",
    ],
    propose: null,
    fallback: "A mood that follows from the purpose and the audience; say which.",
  },
  concept: {
    group: "look",
    priority: "essential",
    ask: "Which of the three concepts should the site be built on?",
    why: 'The one idea ("X as Y") that decides the first screen, the signature moment, the names and the proof; palette and type follow from it (design_guide workflow, step 2).',
    options: [],
    propose:
      "Three concepts from the subject's world, each from a different archetype (one object followed through the page, a borrowed format, the name taken literally…): its one-sentence spine, its first screen, its signature moment and how Framer builds it, and the palette (with its two links, as under palette) and type it implies. Drop any a competitor could use as well.",
    fallback: "The concept you find strongest; say why.",
  },
  palette: {
    group: "look",
    priority: "essential",
    ask: "Brand colors, or the palette the chosen concept implies?",
    why: "The color tokens every section uses.",
    options: [],
    propose:
      "Palettes drawn from the chosen concept's world (its materials, the client's photos, one accent that exists there), each with background, surface, text, muted text, line, accent and the text on the accent as hex values, with AA contrast for text on the background and on the accent. Each palette also says how its background is painted: flat, a gradient (linear, radial, mesh) or a live shader (shaders_read), taken like the colors from something in the concept's world whose tone changes across it (light on a wall, the sky, water, a fading print) and named with that source; flat when nothing there does. Under each palette give two links the user can open and send on, its hex values without # joined by -: https://coolors.co/<every color> (all of them as swatches) and https://www.realtimecolors.com/?colors=<text>-<background>-<accent>-<surface>-<second hue, else muted text> (the palette on a sample site); when its background is a gradient or a shader, a third: https://instantgradient.com/app/<the gradient's colors> (them as a live mesh gradient). Offer them as the options, with the brand colors as one more.",
    fallback: "The first palette you proposed.",
  },
  theme: {
    group: "look",
    priority: "essential",
    ask: "Light, dark, or both with a switch?",
    why: "Both means a dark value on every color token and checking every section twice.",
    options: ["Light only", "Dark only", "Light and dark, following the device"],
    propose: null,
    fallback: "Light only.",
  },
  assets: {
    group: "content",
    priority: "essential",
    ask: "Which assets will they provide: a logo (SVG), photos, video, icons?",
    why: "Without a logo you draw an SVG mark; without photos you search stock (images_search). Every stand-in is named and listed at handoff.",
    options: ["All of them", "Only the logo", "Nothing yet: use stock and placeholders"],
    propose: null,
    fallback: "Stock images and named placeholders, listed at handoff.",
  },
  copy: {
    group: "content",
    priority: "essential",
    ask: "Who writes the text, and in which language?",
    why: "Real copy shapes the layout. Never lorem ipsum; a template gets realistic placeholder copy.",
    options: ["I'll give the texts", "Write real copy, I'll edit it", "Placeholders I'll replace"],
    propose: null,
    fallback: "You write real copy in the site's language.",
  },
  motion: {
    group: "behaviour",
    priority: "essential",
    ask: "How much motion: subtle, balanced or expressive?",
    why: "Which effects to build (design_guide motion, the motion menu).",
    options: [
      "Subtle: fades and hovers",
      "Balanced: reveals, hovers and a ticker",
      "Expressive: scroll scenes, pinned sections and rich hovers",
    ],
    propose: null,
    fallback: "Balanced.",
  },
  audience: {
    group: "project",
    priority: "recommended",
    ask: "Who are the visitors, and what must they believe before they act?",
    why: "The tone of the copy and which proof to show: numbers, logos, reviews or cases.",
    options: [],
    propose: null,
    fallback: "An audience that follows from the purpose; state it in the direction.",
  },
  typography: {
    group: "look",
    priority: "recommended",
    ask: "Brand fonts, or one of the pairings you propose?",
    why: "The text styles.",
    options: [],
    propose:
      "Two or three pairings found with fonts_search and fonts_discover (a workhorse and at most two voices, each with a job), each with why it fits the concept, its license and whether it covers the site's language.",
    fallback: "The first pairing you proposed.",
  },
  imagery: {
    group: "look",
    priority: "recommended",
    ask: "What kind of visuals: photography, product shots, illustration, 3D, video?",
    why: "The hero's composition, which stock to search and how heavy the page gets.",
    options: ["Photography", "Product or interface shots", "Illustration", "3D or abstract", "Video in the hero"],
    propose: null,
    fallback: "Photography, with a video in the hero when it fits.",
  },
  cms: {
    group: "content",
    priority: "recommended",
    ask: "Which content repeats or will grow (blog, case studies, team, reviews, jobs, FAQ, changelog), and who adds new items?",
    why: "CMS collections, with a page per item where it needs one, instead of blocks copied by hand.",
    options: [],
    propose: "The collections this site needs, each with its fields.",
    fallback: "A collection for anything repeated three or more times that will grow.",
  },
  localization: {
    group: "content",
    priority: "recommended",
    ask: "One language or several? Which one is the main one?",
    why: "Framer's localization (locales, translated copy, a language switch in the header); some plans lack it.",
    options: ["One language", "Two or more languages"],
    propose: null,
    fallback: "One language.",
  },
  features: {
    group: "behaviour",
    priority: "recommended",
    ask: "What should the site do besides show content: a contact form, booking, a newsletter, a store, search, a members area, a map, a chat?",
    why: "Forms and integrations. Anything that needs code is said before it is built.",
    options: ["A contact form", "Booking (Cal.com, Calendly)", "A newsletter sign-up", "Nothing beyond links"],
    propose: null,
    fallback: "A contact form, or a mailto link for the main action.",
  },
  seo: {
    group: "launch",
    priority: "recommended",
    ask: "Is there a current site to replace (old addresses to redirect), and words people should find it by?",
    why: "Page titles and descriptions, redirects, the favicon and the social image.",
    options: [],
    propose: null,
    fallback:
      "A title and a description for every page, a favicon and a social image made from the logo, no redirects.",
  },
  handoff: {
    group: "launch",
    priority: "recommended",
    ask: "Who will edit the site after launch, and when is it due?",
    why: "Clear layer names, components and CMS for whoever edits it next, and the order of work against the date.",
    options: ["Me, in Framer", "A client new to Framer", "Nobody: it stays as built"],
    propose: null,
    fallback: "Someone new to Framer: clear layer names, components and the CMS for anything they will change.",
  },
  launch: {
    group: "launch",
    priority: "optional",
    ask: "Is there a domain, and which Framer plan will the site be on?",
    why: "A custom domain, CMS limits, localization and redirects depend on the plan; framer_status shows what the project lacks.",
    options: [],
    propose: null,
    fallback: "Build within the current plan and say what needs a paid one.",
  },
  screens: {
    group: "launch",
    priority: "optional",
    ask: "Do some screens matter more than others, for example most visitors on phones?",
    why: "The breakpoints and where to spend the most care.",
    options: [],
    propose: null,
    fallback: "Desktop 1440, laptop 1280, tablet 810 and phone 390, all equally finished.",
  },
  tracking: {
    group: "launch",
    priority: "optional",
    ask: "Analytics beyond Framer's own: Google Analytics, Tag Manager, Plausible, a cookie banner?",
    why: "Third-party scripts are custom code, added only on request.",
    options: [],
    propose: null,
    fallback: "Framer's built-in analytics only.",
  },
  accessibility: {
    group: "launch",
    priority: "optional",
    ask: "Any accessibility requirements beyond the usual?",
    why: "Contrast, sizes, alt text and focus.",
    options: [],
    propose: null,
    fallback: "WCAG AA contrast, alt text on every image, a visible focus and readable sizes.",
  },
} as const satisfies Record<string, BriefQuestionInfo>;

/** How the AI runs the brief; returned with every call. */
export const BRIEF_INSTRUCTIONS = [
  "Run the brief before building or redesigning a site, in the user's language. Skip whatever the user has already told you and save it as an answer.",
  "Ask in rounds of up to four questions, essentials first, each with its options; the user can always answer in their own words. Where a question has `propose`, make concrete proposals for this project and offer them as the options instead of asking an open question.",
  'When the user skips a question or says "decide yourself", take its fallback and say which.',
  "Save the answers after every round with project_brief { answers }. The brief stays with the project: before any later work on this site, read it with project_brief instead of asking again.",
  "Once the essentials are answered, read design_guide workflow, write out the direction from the brief and start.",
].join(" ");
